version: '3.8'

include:
  - proxy.yaml

services:
  web:
    image: cr.yandex/crp951l9uq6957ruf56i/python-app:test  # Качаю образ из Yandex Container Registry
    restart: always  # Всегда рестартится
    networks:
      backend:
        ipv4_address: 172.20.0.5
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    depends_on:
      - db  # Зависимость от сервиса db

  db:
    image: mysql:8  # Качаю образ из Docker Registry
    restart: always  # Всегда рестартится
    networks:
      backend:
        ipv4_address: 172.20.0.10
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql  # Для сохранения данных MySQL

volumes:
  db-data:  # Выделяю том для хранения днных при пересборке контейнера